[tool.poetry]
name = "oterm"
version = "0.1.0"
description = "A terminal client for ollama."
authors = ["Yiorgis Gozadinos <ggozadinos@gmail.com>"]
license = "GPL"
readme = "README.md"

[tool.poetry.scripts]
oterm = "oterm.cli.oterm:cli"


[tool.poetry.dependencies]
python = "^3.10"
textual = { version = "^0.40.0", extras = ["dev", "syntax"] }
typer = "^0.9.0"
python-dotenv = "^1.0.0"
pydantic = "^2.4.2"

[tool.poetry.group.dev.dependencies]
pdbpp = "^0.10.3"
ruff = "^0.0.292"
black = "^23.9.1"
pytest = "^7.4.2"
pytest-asyncio = "^0.21.1"
textual-dev = "^1.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
